### ISSUE TITLE
Hypergraph data construction

### ISSUE THREAD

**Issue by levtelyatnikov** [jianhao2016/AllSet#10]
Hello, thank you for your work and this repo. I have a curiosity about hypergraph construction procedure:

In the paper you have mentioned that you utilise approached proposed in `[HyperGCN: A New Method of Training Graph Convolutional Networks on Hypergraphs](https://arxiv.org/pdf/1809.02589.pdf)` for the CORA, CITESEER, PUBMED, CORA-CA,  DBLP-CA. The rest datasets:  20Newsgroups, Mushroom, Zoo, ModelNet40 and NTU2012 are constructed based on `[Hypergraph Neural Networks](https://arxiv.org/pdf/1809.09401.pdf)`, `[Hypergraph Learning with Line Expansion](https://arxiv.org/pdf/2005.04843.pdf)`, however ModelNet40 and NTU2012 are presented in both papers, so it is not clear how you have constructed them?

Same it is not clear which technique have you used to construct Yelp, House, and Walmart. 

I am curious about it because I have noticed that some nodes in the datasets are completely isolated (as it depicted in the table)
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/23523959/225077593-c2ad2a49-05bb-4c17-b66b-992e61e33645.png">

For example I have found that CORA has 1200 isolated nodes out of 2708 nodes

**Comment by elichienxD** [comment]
Hi @levtelyatnikov , 

Note that for citation networks (such as cora, citeseer...etc), we directly obtained from the HyperGCN paper (Yadati et al. 2019). Please check their paper and github for how they construct those datasets. For datasets Zoo to ModelNet40, we obtain from the authors of Yang et. al. (2020), where they follow the construction of Feng et al. (2019). We do not create these datasets by ourselves. 

For the three new datasets that we create (Yelp, House and Walmart), I believe we provide enough details in Appendix I. Please let me know if you still have questions after reading it. @jianhao2016 , who create those datasets, might be able to answer additional questions if you still cannot figure it out. 

Regarding the isolated node issue, I personally did not check and it might be the problem of Yadati et al. (2019) when they create their datasets. Can you download the cora dataset from their github and check if the same problem happens there? If so, then at least we have a fair comparison with HyperGCN. It will be interesting to see how to create cora datasets so that there are not that many isolated nodes. If not, please do let me know and I will go into further details and see what would be the potential issue. I'll also ping @jianhao2016 , who prepare the experiment if necessary. 

Thanks,
Eli

**Comment by levtelyatnikov** [comment]
Hi, for now I will stick with current datasets, but it would be interesting to investigate the issue
