### ISSUE TITLE
HyperGCN normalising constant

### ISSUE THREAD

**Issue by Fladmark** [jianhao2016/AllSet#9]
Hi,

I was working on the HyperGCN and noticed that for some datasets (mainly the heterophilic ones) the normalisation constant (c) in the Laplacian method could become negative if the length of the hyperedge was 1. This will result in negative weights, which seems to corrupt a lot of the results you have gotten from the HyperGCN (from the performance row in the paper). I believe you could fix this by simply removing the "-3" on row 112 in utils.py. 

As an example of performance boost: HyperGCN + Mushroom now gives a final test accuracy of 96.69 ± 0.82.

**Comment by elichienxD** [comment]
Hi @Fladmark ,

Thanks for sharing your findings. This is indeed really interesting. We use the same implementation as the official HyperGCN implementation, where they do have the "-3" in their implementation. See [here](https://github.com/malllabiisc/HyperGCN/blob/de049387d8d8c9fe6ebab83cb4b49cacfd4ed534/model/utils.py#L110).

We decide not to modify the code so that it is indeed a "HyperGCN", as it is an intrinsic drawback of their design. In fact, your finding shows that the design of HyperGCN is not suitable for general hypergraph learning. How to design the "normalization constant c" in HyperGCN in a principled way is an interesting question. Yet the real question is whether we should really use the HyperGCN methodology for hypergraph learning. Nevertheless, maybe your finding can lead to a new type of method for hypergraph learning, which I would love to learn if you develop it in the future.

Let me know if you have further questions!

Best,
Eli

**Comment by elichienxD** [comment]
Hi @Fladmark ,

Since there's no follow-up question for about 3 weeks, I will close the issue for now. Nevertheless, please feel free to reopen the issue if you have any further questions. 

Best,
Eli
